---
author: Dustin Dortch
name: Cherry-pick to Release Branch
description: Cherry-picks a commit (based on tag) to a release branch.

inputs:
  prefix:
    default: 'v'
    description: 'Version tag prefix (default: v)'
    required: false
  branch_prefix:
    default: 'release'
    description: 'Branch prefix (default: release)'
    required: false
  tag:
    description: 'Tag to cherry-pick'
    required: true
  default_branch:
    default: ${{ github.event.repository.default_branch }}
    description: 'Default branch'
    required: false

runs:
  using: composite
  steps:
    - name: Set environment variables
      id: set-env
      shell: bash
      run: |
        echo "Set environment variables"
        version="${{ inputs.tag }}"
        RELEASE_VERSION="${version//${{ inputs.prefix }}}" && echo "RELEASE_VERSION=${RELEASE_VERSION}" | tee -a $GITHUB_ENV
        IFS='.' read -r major minor patch <<< $RELEASE_VERSION
        echo "major=${major}" | tee -a $GITHUB_ENV
        echo "minor=${minor}" | tee -a $GITHUB_ENV
        echo "patch=${patch}" | tee -a $GITHUB_ENV
        branch_prefix="${{ inputs.branch_prefix }}" && echo "branch_prefix=${branch_prefix}" | tee -a $GITHUB_ENV
        prefix="${{ inputs.prefix }}" && echo "prefix=${prefix}" | tee -a $GITHUB_ENV
        echo "release_branch=${branch_prefix}/${prefix}${major}.${minor}" | tee -a $GITHUB_ENV
        echo "default_branch=${{ inputs.default_branch }}" | tee -a $GITHUB_ENV
        currentCommitHash=$(git rev-parse ${{ inputs.tag }}^0) && echo "currentCommitHash=${currentCommitHash}" | tee -a $GITHUB_ENV
        echo "cherryPickBranch=cherry-pick/${currentCommitHash}" | tee -a $GITHUB_ENV

    - name: Full git history
      id: git-history
      shell: bash
      run: |
        echo "Full git history"
        cd $GITHUB_WORKSPACE
        git fetch --all
        git pull --all

    
    - name: Create Release Branch (if necessary)
      id: create-release-branch
      shell: bash
      run: >
        echo "Create Release Branch (if necessary)"; 
        cd $GITHUB_WORKSPACE; 
        git checkout --orphan ${{ env.release_branch }} && 
        git commit --allow-empty -m "Release branch ${{ env.release_branch }}" && 
        git push origin ${{ env.release_branch }} && 
        git checkout ${{ env.default_branch }} || true

    - name: Checkout cherry-pick branch
      id: cherry-pick-branch
      shell: bash
      run: |
        echo "Checkout cherry-pick branch"
        cd $GITHUB_WORKSPACE
        git checkout -b ${cherryPickBranch} ${currentCommitHash}
        git push origin ${cherryPickBranch}

    - name: Create PR to Release Branch
      id: pr-to-release-branch
      shell: bash
      run: >
        echo "Create PR to Release Branch"; 
        gh pr create 
        --base ${release_branch} 
        --head ${cherryPickBranch} 
        --title "PR ${cherryPickBranch} to ${release_branch}" 
        --body "PR ${cherryPickBranch} to ${release_branch}"
...